<Workspace Version="0.7.4.3090" X="84.5372771003379" Y="99.8311975102254" zoom="1.545620359375" Description="This node will query a mesh for a face center. " Category="Archi-lab_MantisShrimp.ReadRhino" Name="Get Rhino Mesh Face Center" ID="acc4cdfb-cdb1-4eb5-b42e-756cc1d3d09f">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="23d6c9f2-2509-422f-8082-5feef7a8ba6a" nickname="Python Script" x="250" y="0" isVisible="false" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>#Copyright(c) 2014, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys
clr.AddReference('ProtoGeometry')

RhinoCommonPath = r'C:\Program Files\Rhinoceros 5 (64-bit)\System'
if RhinoCommonPath not in sys.path:
	sys.path.Add(RhinoCommonPath)
clr.AddReferenceToFileAndPath(RhinoCommonPath + r"\RhinoCommon.dll")

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

import Rhino as rc
from Autodesk.DesignScript.Geometry import *
import math

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
rhObjects = IN[0]

#3dPoint Conversion
def rhPoint3dToPoint(rhPoint):
	rhPointX = rhPoint.X
	rhPointY = rhPoint.Y
	rhPointZ = rhPoint.Z
	dsPoint = Point.ByCoordinates(rhPointX, rhPointY, rhPointZ)
	return dsPoint

#convert rhino/gh geometry to ds geometry
dsMeshes = []
values = []
points = []
for i in rhObjects:
	try:
		i = i.Geometry
	except:
		pass
	if i.ToString() == "Rhino.Geometry.Mesh":
		faces = i.Faces
		for i in range(0, faces.Count, 1):
			points.append(rhPoint3dToPoint(faces.GetFaceCenter(i)))
	else:
		message = "Please provide Mesh to extract \nFace Center points."

#Assign your output to the OUT variable
if len(points) == 0:
	OUT = '\n'.join('{:^35}'.format(s) for s in message.split('\n'))
else:
	OUT = points</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="3a2081ca-5ab5-42bd-ab30-a06127855699" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Rhino Object(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="5c23f91b-3781-4f34-9e7b-de61062172ea" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Face Center(s)" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="23d6c9f2-2509-422f-8082-5feef7a8ba6a" start_index="0" end="5c23f91b-3781-4f34-9e7b-de61062172ea" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3a2081ca-5ab5-42bd-ab30-a06127855699" start_index="0" end="23d6c9f2-2509-422f-8082-5feef7a8ba6a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>